student_name = input("Enter your name: ")
student_id = input("Enter your student ID: ")
department = input("Enter your department: ")
year = int(input("Enter your year: "))
university = input("Enter your university: ")
phone = input("Enter your phone number: ")

print("+--------------------------------+")
print("|        AKIBA STUDENT CARD     |")
print("+--------------------------------+")
print(f"| Name: {student_name}     |") 
print(f"| ID: {student_id}         |")
print(f"| Department: {department} |")
print(f"| Year: {year}             |")
print(f"| University: {university} |")
print(f"| Phone: {phone}           |")
print("+--------------------------------+")